from distutils.core import setup, Extension
from wiremaps import VERSION


if __name__ == "__main__":
    setup(name="wiremaps",
          version=VERSION,
          classifiers=[
              'Development Status :: 4 - Beta',
              'Environment :: No Input/Output (Daemon)',
              'Environment :: Web Environment',
              'Framework :: Twisted',
              'Intended Audience :: System Administrators',
              'License :: OSI Approved :: GNU General Public License (GPL)',
              'Operating System :: POSIX',
              'Programming Language :: Python',
              'Topic :: System :: Networking',
          ],
          url='https://github.com/vincentbernat/wiremaps',
          description='layer 2 network discovery application',
          author='Vincent Bernat',
          author_email="bernat@luffy.cx",
          ext_modules=[
              Extension('wiremaps.collector.snmp',
                        libraries=['netsnmp', 'crypto'],
                        sources=['wiremaps/collector/snmp.c']),
          ],
          install_requires=["psycopg2",
                            "Twisted",
                            "Nevow",
                            "IPy",
                            "PyYAML"],
          packages=["wiremaps",
                    "wiremaps.collector",
                    "wiremaps.collector.equipment",
                    "wiremaps.collector.helpers",
                    "wiremaps.web",
                    "wiremaps.core",
                    "twisted.plugins"],
          package_data={'twisted': ['plugins/wiremaps_plugin.py'],
                        'wiremaps.web': ["static/*.png", "static/*.gif",
                                         "static/*.css", "static/*.js",
                                         "main.xhtml",
                                         "images/1.*.png",
                                         "images/unknown.png"]})
