#! /bin/sh

set -e

case "$1" in
    configure)
        for p in $(pyversions -i); do
            $p -c 'from twisted.plugin import IPlugin, getPlugins; list(getPlugins(IPlugin))' >/dev/null 2>&1 || true
        done
        ;;
esac

#DEBHELPER#

exit 0
