#! /bin/sh

set -e

case "$1" in
    remove|purge)
        for p in $(pyversions -i); do
            $p -c 'from twisted.plugin import IPlugin, getPlugins; list(getPlugins(IPlugin))' >/dev/null 2>&1 || true
        done
        ;;
esac

#DEBHELPER#

if [ "$1" = "purge" ]; then
    deluser --system wiremaps || true
    delgroup --system wiremaps || true
    rm -rf /var/run/wiremaps
    rm -rf /var/log/wiremaps
fi

exit 0
