#! /bin/sh

set -e

user=wiremaps
group=wiremaps

if ! ([ "$1" = "configure" ] || [ "$1" = "reconfigure" ]); then
  exit 0
fi

[ -d /var/log/wiremaps ] || mkdir /var/log/wiremaps
[ -d /var/run/wiremaps ] || mkdir /var/run/wiremaps
adduser --system --disabled-password --disabled-login --home /var/run/wiremaps \
         --no-create-home --quiet --group $user
chown $user.$group /var/run/wiremaps
chown $user.$group /var/log/wiremaps

#DEBHELPER#

case "$1" in
    configure)
        for p in $(pyversions -i); do
            $p -c 'import wiremaps.collector ; from twisted.plugin import IPlugin, getPlugins; list(getPlugins(IPlugin)) ; list(getPlugins(IPlugin, wiremaps.collector))' >/dev/null 2>&1 || true
        done
        ;;
esac

exit 0
